name: savvy_bee_mobile
description: "An AI-powered financial literacy and management app"
publish_to: 'none'
version: 1.0.0+13

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  camera: ^0.11.2+1
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  dio: ^5.4.1
  encrypt: ^5.0.3
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.1
  # flutter_unity_widget:
  #   path: local_plugins/flutter_unity_widget
    # git:
    #   url: https://github.com/juicycleff/flutter-unity-view-widget.git
    #   ref: master
  gap: ^3.0.1
  go_router: ^13.2.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  mime: ^2.0.0
  mono_connect: ^2.1.0
  purchases_flutter: ^9.11.0
  purchases_ui_flutter: ^9.11.0
  readmore: ^3.0.0
  riverpod: ^2.6.1
  scroll_indicator: ^0.0.3
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  pointycastle: ^3.7.3
  http: ^1.1.0
  convert: ^3.1.1
  webview_flutter: ^4.9.0
  fl_chart: ^0.68.0
  pdf: ^3.10.4
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  share_plus: ^12.0.1
  csv: ^6.0.0
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  mixpanel_flutter: ^2.3.1
  # flutter_local_notifications: ^16.3.0
  device_info_plus: ^10.1.2
  screenshot: ^3.0.0  # For capturing widget as image

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - .env
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/illustrations/
    - assets/images/illustrations/avatars/
    - assets/images/other/
    - assets/images/game/
    - assets/icons/
    - assets/data/courses/
    - assets/images/other/bee_onboarding_img.png
    - assets/images/topbar/nav-left-icon.png
    - assets/images/topbar/nav-center-icon.png
    - assets/icons/Calculator.png
    - assets/icons/Square-Check.png
    - assets/icons/BookOpen.png
    - assets/images/other/learn-one.jpg
    - assets/images/other/learn-two.jpg
    - assets/images/other/learn-three.jpg
    - assets/images/other/insights-one.jpg
    - assets/images/other/insights-two.jpg
    - assets/images/other/insights-three.jpg
    - assets/images/icons/budget_icon.png
    - assets/images/icons/goals_icon.png
    - assets/images/icons/debt_icon.png
    - assets/images/icons/tax_icon.png
    - assets/images/icons/budget_category.png
    - assets/images/icons/Vacation.png
    - assets/images/illustrations/health/stabilizing.png
    - assets/images/illustrations/health/surviving.png
    - assets/images/illustrations/health/flourishing.png
    - assets/images/illustrations/health/thriving.png
    - assets/images/illustrations/health/building.png
    - assets/images/icons/Wallet.png
    - assets/images/icons/Tree.png
    - assets/images/icons/Vacation.png
    - assets/images/icons/Milestone.png
    - assets/images/Financial_Health/POP UPS/HIVEBARHALTHTIPS.png
    - assets/images/Financial_Health/JARS/HIVE BAR BUILDING.png
    - assets/images/Financial_Health/JARS/HIVE BAR EMPTY.png
    - assets/images/Financial_Health/JARS/HIVE BAR FLOURISHING.png
    - assets/images/Financial_Health/JARS/HIVE BAR STABILISING.png
    - assets/images/Financial_Health/JARS/HIVE BAR SURVIVING.png
    - assets/images/Financial_Health/JARS/HIVE BAR THRIVING.png
    - assets/images/lessons/BUDGETING/L2 BUDGETING.png
    - assets/images/lessons/BUDGETING/L3 BUDGETING.png
    - assets/images/lessons/BUDGETING/L4 BUDGETING.png
    - assets/images/lessons/BUDGETING/L5 BUDGETING.png
    - assets/images/lessons/BUDGETING/LV1 BUDGETING.png
    - assets/images/lessons/NUMERACY_/L1 NUMERACY.png
    - assets/images/lessons/NUMERACY_/L2 NUMERACY.png
    - assets/images/lessons/NUMERACY_/L4 NUMERACY.png
    - assets/images/lessons/NUMERACY_/L5 NUMERACY.png
    - assets/images/lessons/NUMERACY_/LV3 NUMERACY.png
    - assets/images/lessons/SAVINGS_/L1 SAVINGS.png
    - assets/images/lessons/SAVINGS_/L3 SAVINGS.png
    - assets/images/lessons/SAVINGS_/L4 SAVINGS.png
    - assets/images/lessons/SAVINGS_/L5 SAVINGS.png
    - assets/images/lessons/SAVINGS_/LV2 SAVINGS.png
    - assets/images/other/BLUE FLOWER - Flight Boost.png
    - assets/images/acheivements/7 DAY STREAK.png
    - assets/images/acheivements/BUSY BEE BADGE.png
    - assets/images/acheivements/BUZZING BEGINNER.png
    - assets/images/acheivements/POLLEN PRO.png
    - assets/images/acheivements/SUSU FIRST FLIGHT.png
    - assets/images/icons/bottomtab/dashboard.png
    - assets/images/icons/bottomtab/hive.png
    - assets/images/icons/bottomtab/home.png
    - assets/images/icons/bottomtab/tools.png
    - assets/images/walk_through/home_arrow.png
    - assets/images/walk_through/home_welcome.png
    - assets/images/walk_through/home_cheerful.png
    - assets/images/walk_through/home_budget.png
    - assets/images/walk_through/dashboard.png
    - assets/images/walk_through/boo.png
    - assets/images/walk_through/debts.png
    - assets/images/walk_through/debts_welcome.png
    - assets/images/walk_through/goals.png
    - assets/images/walk_through/taxes.png
    - assets/images/walk_through/tools_welcome.png
    - assets/images/other/PINK FLOWER - CURRENCY.png
    - assets/images/other/SUN.png
    - assets/images/icons/LEAGUE ICONS/BUMBLE LEAGUE.png
    - assets/images/icons/LEAGUE ICONS/HONEY LEAGUE.png
    - assets/images/icons/LEAGUE ICONS/MASON LEAGUE.png
    - assets/images/icons/LEAGUE ICONS/ORCHID LEAGUE.png
    - assets/images/icons/LEAGUE ICONS/QUEEN BEE.png
    - assets/images/icons/LEAGUE ICONS/QUEENSGUARD.png
    - assets/images/icons/LEAGUE ICONS/ROYAL LEAGUE.png
    - assets/images/icons/loki.png
    - assets/images/icons/dash.png
    - assets/images/icons/penny.png
    - assets/images/icons/bloom.png
    - assets/images/icons/susu.png
    - assets/images/icons/luna.png
    - assets/images/icons/boo.png

  fonts:
    - family: Excon
      fonts:
        - asset: assets/fonts/excon/Excon-Black.otf
        - asset: assets/fonts/excon/Excon-Bold.otf
        - asset: assets/fonts/excon/Excon-Medium.otf
        - asset: assets/fonts/excon/Excon-Regular.otf

    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsans/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/generalsans/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/generalsans/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/generalsans/GeneralSans-Regular.otf
          weight: 400

    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka/Fredoka-SemiBold.ttf
        - asset: assets/fonts/fredoka/Fredoka-Bold.ttf

    - family: Londrina Solid
      fonts:
        - asset: assets/fonts/londrina-solid/LondrinaSolid-Regular.ttf
          weight: 400
        - asset: assets/fonts/londrina-solid/LondrinaSolid-Black.ttf
          weight: 900
