// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjSh_9zM7W7mKYaRphrZebNT860vR30_I',
    appId: '1:581876547334:web:df42d48239db4a3adea887',
    messagingSenderId: '581876547334',
    projectId: 'the-app-stopper',
    authDomain: 'the-app-stopper.firebaseapp.com',
    storageBucket: 'the-app-stopper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqgpmrEqPxqh9FkhaiGjpyX9bhw9WYces',
    appId: '1:581876547334:android:cbff29eb43c669b5dea887',
    messagingSenderId: '581876547334',
    projectId: 'the-app-stopper',
    storageBucket: 'the-app-stopper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDboU6PRoQATtCWCIYH9kd16Euk0sNblc',
    appId: '1:581876547334:ios:eafe769d1a3f9a9cdea887',
    messagingSenderId: '581876547334',
    projectId: 'the-app-stopper',
    storageBucket: 'the-app-stopper.firebasestorage.app',
    iosBundleId: 'com.example.savvyBeeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDboU6PRoQATtCWCIYH9kd16Euk0sNblc',
    appId: '1:581876547334:ios:eafe769d1a3f9a9cdea887',
    messagingSenderId: '581876547334',
    projectId: 'the-app-stopper',
    storageBucket: 'the-app-stopper.firebasestorage.app',
    iosBundleId: 'com.example.savvyBeeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjSh_9zM7W7mKYaRphrZebNT860vR30_I',
    appId: '1:581876547334:web:68db47afe7dce96ddea887',
    messagingSenderId: '581876547334',
    projectId: 'the-app-stopper',
    authDomain: 'the-app-stopper.firebaseapp.com',
    storageBucket: 'the-app-stopper.firebasestorage.app',
  );
}
